### PR TITLE
Add write and read raw data

### PR DESCRIPTION
**Pull request by aioue**
Full credit to 'Chuck' : https://stackoverflow.com/a/50859586/1053741

They created a very useful enhancement.

### CODE REVIEW

**Comment by tomoh1r** [comment]
I'll check it, but first, I think, I need to permit to use it.

**Comment by cwurld** [comment]
Hi. This is Chuck. I approve.
Actually, I am honored that you want to add my snippet. Keep up the good work!

**Comment by tomoh1r** [comment]
@cwurld Thanks, I check this!

**Comment by AdnanSaid** [comment]
Hi @cwurld I had a question, upon using the code as given by Kuba, it worked to just unlock the file and show the playbook I locked in the vault, is there a way to use the python script to unlock then run the playbook?

**Comment by aioue** [comment]
@AdnanSaid that's not what the script is for. Just run the playbook as usual after unlock. If you pass the vault decrypt password you don't even need to unlock before a playbook run, it's all done transparently by ansible.

**Pull request merged**
