### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by ahosking**
Update the example to show a write in Python 3.

### CODE REVIEW

**Comment by tomoh1r** [comment]
I see, perhaps, the library need to adjust the file mode and the encoding.

The mode can detect `fp.mode`. But, shoud the library detect the encoding from system environment, or other?

I'll investigate.

If it shout do, I'll change p-r title, sorry.

**Comment by ahosking** [comment]
No problem.

I spent a bunch of time trying to figure out why it worked in one environment and not the other.
I'll look at adapting the code to determine that for a user, but this was the easiest way to update folks now.

**Comment by tomoh1r** [comment]
> but this was the easiest way to update folks now.

Yes, I agree with you.

But, this library is aim to wrap ansible-vault yaml file. Because of this, if yaml library work so, this library too.

And the issue point is [api.py#L60](https://github.com/tomoh1r/ansible-vault/blob/master/ansible_vault/api.py#L60). I need to investigate and determine the direction.

**Comment by ahosking** [comment]
I'm also looking to see if there is a reasonable way to fix this.
There is little mention of this between python versions from what I've found thus far.

**Comment by ahosking** [comment]
If you merge the pull request for the API update, you can then delete this one as the end user method doesn't change between python versions.

**Pull request closed without merging**
